[package]
name = "testless-core"
version = "0.3.0"
edition.workspace = true
description = "testless graph core"
repository.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.104"
bincode = "1"
blake3 = "1.8.5"
ignore = "0.4.31"
serde = { version = "1.0.229", features = ["derive"] }
tree-sitter = "0.26.11"

[dev-dependencies]
tempfile = "3.27.0"
tree-sitter-typescript = "0.23.2"
