[package]
name = "testless-lang-rust"
version = "0.5.1"
edition.workspace = true
description = "Rust language plugin for testless"
repository.workspace = true
license.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
testless-core = { path = "../core", version = "0.5.1" }
tree-sitter = "0.26.11"
tree-sitter-rust = "0.24.2"
